#!/bin/bash

echo "AUFRUF MIT ./run euler.f95"

echo "============================================================="
echo "LADE AUF GITHUB HOCH"


git commit -a -m "ich habe wieder etwas weitergearbeitet"
git push

echo "============================================================="
echo "KOMPILIEREN UND STARTEN"

# Auskommentieren mit #
# f95 RungeKuttaNeu.f95 -o RungeKuttaNeuProg && ./RungeKuttaNeuProg

Basisname=basename $1 .f95

f95 $1 -o $Basisname && ./$Basisname | tee schleifentest.txt 


echo "============================================================="
echo "JETZT KOMMT GNUPLOT "
# gnuplot...